version: 2.1

jobs:
  build:
    docker:
      - image: circleci/3.8-slim-buster # Change to the base image your project uses
    steps:
      - checkout

      # Setup Docker
      - setup_remote_docker:
          version: 20.10.7

      # Install Docker client
      - run:
          name: Install Docker client
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-ce-cli

      # Build Docker image
      - run:
          name: Build Docker image
          command: docker build -t fraidoonjan/nlp-app:latest .

      # Log in to Docker Hub
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      # Push Docker image to Docker Hub
      - run:
          name: Push Docker image
          command: docker push fraidoonjan/nlp-app:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
