version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Changed to a more general and commonly available tag
    steps:
      - checkout

      # Setup Docker environment
      - setup_remote_docker:
          version: 20.10.7

      # Build Docker image
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/nlp-app:latest .

      # Debug: List Docker images
      - run:
          name: List Docker images
          command: docker images

      # Log in to Docker Hub
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      # Debug: Confirm Docker login
      - run:
          name: Confirm Docker login
          command: docker info

      # Push Docker image to Docker Hub
      - run:
          name: Push Docker image
          command: docker push $DOCKERHUB_USERNAME/nlp-app:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
